base_model: meta-llama/Meta-Llama-3-70B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: Kindroid/v4-4096
    ds_type: jsonl
    type:
      system_prompt: ""
      field_instruction: input
      format: "{instruction}"
      no_input_format: "{instruction}"
dataset_prepared_path:
val_set_size: 0
output_dir: ./70b-base-qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 16
lora_dropout: 0.00
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: v4-fine-tune
wandb_entity: kindroid
wandb_watch:
wandb_name:
wandb_log_model:

hub_model_id: Kindroid/v4-70B-Base
hub_strategy: all_checkpoints

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_32bit
lr_scheduler: constant
learning_rate: 0.0004

train_on_inputs: false
group_by_length: true
bf16: auto
fp16:
tf32: false

max_grad_norm: 0.3
gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps:
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|end_of_text|>"
